name: minda_application
description: "Minda application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.15
  flutter_screenutil: ^5.9.3
  tutorial_coach_mark: ^1.2.12
  shared_preferences: ^2.3.3
  rive: ^0.13.20
  device_info_plus: ^11.1.1
  flutter_verification_code_field: ^1.0.9
  date_input_form_field: ^1.2.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  fl_chart: ^0.70.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/minda_logo.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background/
    - assets/icons/
    - assets/images/
    - assets/icons/
    - assets/rive_files/
    - lib/src/ui/screens/child/
    - assets/
    - assets/logo/
    - assets/fonts/
    - assets/fonts/Sriracha/
    - lib/src/repositories/
    - lib/src/ui/screens/parent/
    - lib/
    - lib/src/
    - lib/src/ui/
    - lib/src/ui/common/
    - lib/src/ui/themes/
    - lib/src/ui/screens/
    - lib/src/ui/screens/welcome/
    - lib/src/ui/widgets/
    - lib/src/blocs/
    - lib/src/blocs/child/
    - lib/src/blocs/parent/
    - lib/src/utils/
    - lib/src/utils/themes/
    - lib/src/utils/themes/custom_themes/
    - lib/src/config/
    - lib/src/models/
    - lib/src/models/parent/
    - lib/src/services/
    - lib/src/data_provider/
    - lib/generated/

  fonts:
    - family: Sriracha
      fonts:
        - asset: assets/fonts/Sriracha/Sriracha-Regular.ttf
          style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
